### ISSUE TITLE
NNbenchmark

### ISSUE THREAD

**Issue by gangliao** [gangliao/docs#1]
We use the default configuration: the max heap size for HDFS is 1 GB.

When we create a large number of files, nnbenchmark will be failed.

```bash
xception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.apache.hadoop.hdfs.server.namenode.FileNameGenerator.getNextFileName(FileNameGenerator.java:75)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark$CreateFileStats.generateInputs(NNThroughputBenchmark.java:587)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark$OperationStatsBase.benchmark(NNThroughputBenchmark.java:260)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.run(NNThroughputBenchmark.java:1553)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.runBenchmark(NNThroughputBenchmark.java:1453)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.main(NNThroughputBenchmark.java:1579)
```

It failed due to fileNames is too large.

```bash
          fileNames[idx][jdx] = nameGenerator.
                                  getNextFileName("ThroughputBench");
```
We might increase the max heap size for the scalability test.

**Comment by gangliao** [comment]
From https://docs.cloudera.com/HDPDocuments/HDP2/HDP-2.4.2/bk_installing_manually_book/content/ref-80953924-1cbf-4655-9953-1e744290a6c3.1.html,
10-20 million files require 9984m of the heap size.


I will use t3a.2xlarge for HDFS client.

Instance Type | ECUs | vCPUs | Memory (GiB) | Instance Storage (GB) | EBS-Optimized Available | Network Performance
-- | -- | -- | -- | -- | -- | --
t3a.2xlarge | Variable | 8 | 32 | EBS only | Yes | Up to 5 Gigabit
